---
- name: Install Apache with PHP support
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP support
      apt:
        name: libapache2-mod-php
        state: present

